export const copy = {
  appName: "Immonator",
  appTagline: "German Real Estate Analysis",
  betaBadge: "BETA",

  nav: {
    properties: "Properties",
    portfolio: "Portfolio",
    markets: "Markets",
    strategy: "Strategy",
    feedback: "Feedback",
    signOut: "Sign Out",
  },

  landing: {
    headline: "Know exactly what a property is worth before you offer.",
    subtext:
      "Immonator analyses every German property listing using official valuation methods — in seconds.",
    ctaPrimary: "Get Early Access →",
    ctaHint: "Invite only · No credit card needed",
    featurePills: [
      "✓ Ertragswert & Sachwert",
      "✓ AI investment verdict",
      "✓ Negotiation brief",
    ],
    quoteText:
      "I saved €18,000 on my first offer because Immonator showed me the property was overpriced.",
    quoteAttrib: "Early access member, Berlin",
    finalCta: "Start analysing properties →",
  },

  login: {
    headline: "Welcome to Immonator",
    subtext: "Enter your invite code to get started.",
    codePlaceholder: "e.g. IMMO-BCDF",
    codeLabel: "Beta Access Code",
    nameLabel: "Your name (optional)",
    submitButton: "Get Started →",
    invalidCode: "Invalid code. Check your invite.",
    revokedCode: "This access code has been deactivated. Contact us for help.",
  },

  analysis: {
    analysingText: "Immonator is analysing this property...",
    deepAnalysingText: "Immonator is running a full analysis...",
    portfolioAnalysingText: "Immonator is reviewing your portfolio...",
    strategyGeneratingText: "Immonator is building your strategy...",
    aiLabel: "Immonator AI",
    aiTimestamp: "Immonator AI · Just now",
    aiJustNow: "Just now",
    progressSteps: [
      "Calculating valuations...",
      "Assessing investment case...",
      "Evaluating risks...",
      "Preparing recommendations...",
    ],
    deepAnalysisButton: "Run Full Analysis",
    deepAnalysisHint: "Takes 10-20 seconds · Saved for 24 hours",
    runDeepAnalysis: "Run Deep Analysis",
    confidence: "Confidence",
    confidenceScale: "/10",
    positives: "POSITIVES",
    risks: "RISKS",
    ifMyMoney: "If this were my money:",
    fairlyPriced: "Fairly Priced",
    overpriced: "Overpriced",
    riskSuffix: "risk",
    downloadPdf: "Download PDF",
    pdfProTitle: "Available in Pro plan",
    pdfProDescription:
      "PDF export is available on the Pro plan. Join the waitlist to be notified when it launches.",
    loadingMessages: [
      "Calculating valuations...",
      "Analysing risk factors...",
      "Running financing scenarios...",
      "Evaluating market context...",
      "Generating AI verdict...",
      "Compiling report...",
    ],
    sectionTitles: [
      "Executive Summary",
      "Property Assessment",
      "Valuation Analysis",
      "Investment Case",
      "Risk Analysis",
      "Financing",
      "Market Context",
      "Action Plan",
    ],
    financingLabels: {
      ltv: "LTV:",
      payment: "Payment:",
      cashflow: "Cashflow:",
      equity: "Equity:",
    },
  },

  market: {
    suffix: "Market",
    avgPricePerSqmLabel: "Avg",
    avgDaysLabel: "Avg",
    viewFullReport: "View Full Report →",
  },

  scenarioModeller: {
    monthlyCashflow: "Monthly Cashflow",
    perMonthAfterCosts: "per month after all costs",
    analysing: "Analysing scenario...",
    save: "Save",
    saveScenario: "Save This Scenario",
    savedScenariosPlaceholder: "Saved Scenarios ▾",
  },

  chat: {
    headerPrefix: "Chat about",
    inputPlaceholder: "Ask anything...",
    errorGeneric: "Sorry, something went wrong. Please try again.",
    errorNetwork: "Connection error. Please try again.",
    aiLabel: "Immonator AI",
    advisor: {
      subtitle: "Uses the current property analysis context for follow-up questions and guidance.",
      emptyStateTitle: "How can I help?",
      emptyStateDescription:
        "I have the current property analysis context and will add Full Review and Buying Strategy details when they are available.",
      inputPlaceholder: "Ask the advisor about this analysis…",
    },
    suggestions: [
      "Is this a good investment?",
      "What's a fair offer price?",
      "What are the main risks?",
      "How does this fit my strategy?",
      "Explain the numbers to me",
    ],
  },

  portfolio: {
    analysisEmptyHeadline: "Compare your shortlist.",
    analysisEmptyBody:
      "Immonator ranks properties and shows which to prioritise and how to deploy capital.",
    analysisEmptyCta: "Analyse My Portfolio",
    rankingsLabel: "Rankings",
    actionPlanLabel: "Action Plan",
    tableHeaders: {
      property: "Property",
      allocation: "Allocation",
      priority: "Priority",
      status: "Status",
      price: "Price",
      verdict: "Verdict",
      yield: "Yield",
      days: "Days",
      gap: "Gap%",
    },
    contextHintHeadline: "Compare your shortlist",
    contextHintBody: "See which properties to prioritise.",
    browseCta: "Browse Properties →",
    analysing: "Analysing...",
    emptyHeadline: "Your portfolio is empty.",
    emptyBody: "Save a property to get an instant AI verdict.",
  },

  strategy: {
    wizard: {
      step1Title: "How much equity do you have available?",
      step1Hint: "Available cash for down payment and closing costs",
      step2Title: "Your monthly finances",
      step2Income: "Income",
      step2Expenses: "Expenses",
      step3Title: "What's your investment style?",
      step3HoldLabel: "How long to hold?",
      step4Title: "What matters most?",
      step4YieldLabel: "Minimum gross yield:",
      step4YieldSuffix: "% minimum",
      step5Title: "Where do you want to invest?",
      continue: "Continue",
      generate: "Generate My Strategy",
    },
    emptyTitle: "What should you be buying?",
    emptyBody:
      "Tell Immonator your equity, risk profile, and goals. We will match you with the right cities, yields, and financing structures for your budget.",
    buildCta: "Build My Strategy",
    pills: ["Target cities", "Yield thresholds", "Financing"],
    editProfile: "Edit Profile",
    targetYield: "Target Yield",
    maxPrice: "Max Price",
    timeline: "Timeline",
    financingHeaders: {
      type: "Type",
      rate: "Rate",
      ltv: "LTV",
    },
    recommended: "REC",
    topMatches: "Top Matches",
    viewAll: "View All",
  },

  toasts: {
    saved: "Saved. Immonator is analysing...",
    analysisReady: (verdict: string) => `Analysis ready — ${verdict}`,
    firstSave: "Nice. Check back in ~15 seconds for your verdict.",
    error: "Something went wrong. Please try again.",
  },

  errors: {
    network: "Connection error. Check your internet and try again.",
    unauthorized: "Your session has expired. Please log in again.",
    generic: "Something went wrong. Please try again.",
    invalidCode: "Invalid code. Check your invite.",
    revokedCode: "This access code has been deactivated.",
  },
} as const;
