export const TEST_IDS = {
  IMPORT_PREVIEW: "import-preview",
  IMPORT_MISSING_FIELDS: "import-missing-fields",
  IMPORT_SNAPSHOT_ACTION: "import-snapshot-action",
  IMPORT_REVIEW_ACTION: "import-review-action",
  AI_SNAPSHOT_ACTION: "ai-snapshot-action",
  AI_REVIEW_ACTION: "ai-review-action",
  AI_STRATEGY_ACTION: "ai-strategy-action",
  AI_ADVISOR_LIGHT_ACTION: "ai-advisor-light-action",
  AI_ADVISOR_FULL_ACTION: "ai-advisor-full-action",
  AI_SNAPSHOT_RESULT: "ai-snapshot-result",
  AI_REVIEW_RESULT: "ai-review-result",
  AI_STRATEGY_RESULT: "ai-strategy-result",
  AI_ADVISOR_CHAT: "ai-advisor-chat",
} as const
